### ISSUE TITLE
TODO Experimental Recode

### ISSUE THREAD

**Issue by Outfenneced** [Outfenneced/mesa#1]
- [x] Separate calendars into users
- [x] Re-code searches to go through user->calendar
- [x] Test for functionality
- [x] Test for efficiency
- [x] Remove unnecessary/unused code
- [ ] If more efficient, merge back into jnick1/mesa

**Comment by Outfenneced** [comment]
So, the latest commit is approximately 60 times faster than the previous version. I will be requesting a merge back into jnick1/mesa momentarily and opening for discussion.
